/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package UI;

import DAO.CourseDao;
import DaoImp.CourseDAOImpl;
import java.util.List;
import javax.swing.ImageIcon;
import javax.swing.JButton;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableModel;
import model.Course;
import model.Department;

/**
 *
 * @author 20CS008
 */
public class CourseFrame extends javax.swing.JFrame {

     CourseDao crsDAO = new CourseDAOImpl();
     String[] column = {"ID","C.Name","C.Marks"};
    DefaultTableModel defaultTableModel = null;
    private Course course;
    public CourseFrame() {
        initComponents();
        fillStudentTable();
    /**
     * Creates new form CourseFrame
     */
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    
    private void fillStudentTable(){
           defaultTableModel = new DefaultTableModel(column,0);
      List<Course> list =  crsDAO.getAllCourse();
       
           for(Course c:list ){
            Object[] row = {c.getCourse_id(),c.getCourse_name(),c.getCourse_marks()};
            defaultTableModel.addRow(row);
            crsTable.setModel(defaultTableModel);
        }
       
       
    }
    
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        crsid = new javax.swing.JTextField();
        crsname = new javax.swing.JLabel();
        crsmark = new javax.swing.JLabel();
        txtcrsname = new javax.swing.JTextField();
        txtcrsmark = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        crsTable = new javax.swing.JTable();
        crsclearbtn = new javax.swing.JButton();
        crsaddbtn1 = new javax.swing.JButton();
        crsupbtn1 = new javax.swing.JButton();
        crsdltbtn1 = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(33, 125, 194));

        jPanel2.setBackground(new java.awt.Color(26, 34, 56));
        jPanel2.setForeground(new java.awt.Color(255, 255, 255));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Course");

        jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icon/back btn.png"))); // NOI18N
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addGap(37, 37, 37)
                .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(265, 265, 265)
                .addComponent(jLabel1)
                .addContainerGap(325, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(31, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1))
                .addGap(18, 18, 18))
        );

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(26, 34, 56));
        jLabel2.setText("Course ID");

        crsname.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        crsname.setForeground(new java.awt.Color(26, 34, 56));
        crsname.setText("Course Name");

        crsmark.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        crsmark.setForeground(new java.awt.Color(26, 34, 56));
        crsmark.setText("Course Marks");

        crsTable.setBackground(new java.awt.Color(157, 170, 242));
        crsTable.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        crsTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "Corse ID", "Course Name", "Course Marks"
            }
        ));
        crsTable.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                crsTableMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(crsTable);

        crsclearbtn.setBackground(new java.awt.Color(244, 219, 125));
        crsclearbtn.setFont(new java.awt.Font("Segoe UI", 3, 18)); // NOI18N
        crsclearbtn.setForeground(new java.awt.Color(26, 34, 56));
        crsclearbtn.setText("CLEAR");
        crsclearbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                crsclearbtnActionPerformed(evt);
            }
        });

        crsaddbtn1.setBackground(new java.awt.Color(244, 219, 125));
        crsaddbtn1.setFont(new java.awt.Font("Segoe UI", 3, 18)); // NOI18N
        crsaddbtn1.setForeground(new java.awt.Color(26, 34, 56));
        crsaddbtn1.setText("ADD");
        crsaddbtn1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                crsaddbtn1ActionPerformed(evt);
            }
        });

        crsupbtn1.setBackground(new java.awt.Color(244, 219, 125));
        crsupbtn1.setFont(new java.awt.Font("Segoe UI", 3, 18)); // NOI18N
        crsupbtn1.setForeground(new java.awt.Color(26, 34, 56));
        crsupbtn1.setText("UPDATE");
        crsupbtn1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                crsupbtn1ActionPerformed(evt);
            }
        });

        crsdltbtn1.setBackground(new java.awt.Color(244, 219, 125));
        crsdltbtn1.setFont(new java.awt.Font("Segoe UI", 3, 18)); // NOI18N
        crsdltbtn1.setForeground(new java.awt.Color(26, 34, 56));
        crsdltbtn1.setText("DELETE");
        crsdltbtn1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                crsdltbtn1ActionPerformed(evt);
            }
        });

        jPanel3.setBackground(new java.awt.Color(26, 34, 56));

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 93, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(48, 48, 48)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 564, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGroup(jPanel1Layout.createSequentialGroup()
                                    .addGap(124, 124, 124)
                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addComponent(txtcrsmark, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(crsid, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGap(252, 252, 252)
                                    .addComponent(txtcrsname, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(crsaddbtn1, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(crsupbtn1)
                                .addGap(242, 242, 242)
                                .addComponent(crsclearbtn, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(14, 14, 14)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel2)
                            .addComponent(crsmark))
                        .addGap(274, 274, 274)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(crsdltbtn1, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(crsname))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addComponent(jPanel3, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(crsid, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(crsname)
                    .addComponent(txtcrsname, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(34, 34, 34)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(crsmark)
                    .addComponent(txtcrsmark, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 29, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(crsaddbtn1, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(crsupbtn1, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(crsdltbtn1, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(crsclearbtn, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(35, 35, 35)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 173, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(34, 34, 34)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void crsclearbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_crsclearbtnActionPerformed
        // TODO add your handling code here:
         clearField();
    }//GEN-LAST:event_crsclearbtnActionPerformed

    private void crsaddbtn1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_crsaddbtn1ActionPerformed
        // TODO add your handling code here:
         int id = Integer.parseInt(crsid.getText());
          String name = txtcrsname.getText();
         int courseMarks=Integer.parseInt(txtcrsmark.getText());
            
             Course course = new Course();
             course.setCourse_id(id);
             course.setCourse_name(name);
             course.setCourse_marks(courseMarks);
       
       crsDAO.addCourse(course);
        fillStudentTable();
        clearField();
    }//GEN-LAST:event_crsaddbtn1ActionPerformed

    private void crsupbtn1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_crsupbtn1ActionPerformed
        // TODO add your handling code here:
         int id = Integer.parseInt(crsid.getText());
          String name = txtcrsname.getText();
         int courseMarks=Integer.parseInt(txtcrsmark.getText());
            
             Course course = new Course();
             course.setCourse_id(id);
             course.setCourse_name(name);
             course.setCourse_marks(courseMarks);
       
       crsDAO.updateCourse(course);
        fillStudentTable();
        clearField();
        
    }//GEN-LAST:event_crsupbtn1ActionPerformed

    private void crsdltbtn1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_crsdltbtn1ActionPerformed
        // TODO add your handling code here:
         int id=Integer.parseInt(crsid.getText());
        Course sc = new Course();
        sc.setCourse_id(id);
        crsDAO.deleteCourse(sc);
        fillStudentTable();
       
    }//GEN-LAST:event_crsdltbtn1ActionPerformed

    private void crsTableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_crsTableMouseClicked
        // TODO add your handling code here:
          int index = crsTable.getSelectedRow();
        TableModel model = crsTable.getModel();
        
        String id = model.getValueAt(index, 0).toString();
        String name = model.getValueAt(index, 1).toString(); 
        String marks = model.getValueAt(index, 2).toString();
        
        crsid.setText(id);
        txtcrsname.setText(name);
        txtcrsmark.setText(marks);
        
    }//GEN-LAST:event_crsTableMouseClicked

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        new HomeFrame().setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_jButton2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CourseFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CourseFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CourseFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CourseFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CourseFrame().setVisible(true);
            }
        });
    }
      private void clearField(){
        crsid.setText("");
        txtcrsname.setText("");
        txtcrsmark.setText("");
        
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTable crsTable;
    private javax.swing.JButton crsaddbtn1;
    private javax.swing.JButton crsclearbtn;
    private javax.swing.JButton crsdltbtn1;
    private javax.swing.JTextField crsid;
    private javax.swing.JLabel crsmark;
    private javax.swing.JLabel crsname;
    private javax.swing.JButton crsupbtn1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField txtcrsmark;
    private javax.swing.JTextField txtcrsname;
    // End of variables declaration//GEN-END:variables

   
}
